/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#ifndef APPLICATION_H
#define APPLICATION_H

#include <BCDS_Retcode.h>
#include "applicationTypes.h"


Retcode_T initGlobalVariables_application();

#endif
