/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <BCDS_Environmental.h>
#include <BCDS_LightSensor.h>
#include <XdkSensorHandle.h>
#include <BCDS_Gyroscope.h>
#include <stdint.h>
#include <bma2x2.h>
#include <stdbool.h>
#include "ConnectivityMQTTQubitroBroker.h"
#include "SensorEnvironment.h"
#include "SensorLight.h"
#include "SensorGyroscope.h"
#include "SensorAccelerometer.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif


Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	return exception;
}

Retcode_T HandleEvery10Second1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	struct bma2x2_accel_data sensorAccelerometerModalityPreparation_1;
	exception = SensorAccelerometer_ReadXYZ(&sensorAccelerometerModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	int32_t accx;
	accx = sensorAccelerometerModalityPreparation_1.x;
	int32_t accy;
	accy = sensorAccelerometerModalityPreparation_1.y;
	int32_t accz;
	accz = sensorAccelerometerModalityPreparation_1.z;
	CalibratedGyro_XyzDpsData_T sensorGyroscopeModalityPreparation_2;
	exception = CalibratedGyro_readXyzDpsValue(&sensorGyroscopeModalityPreparation_2);
	if(exception != NO_EXCEPTION) return exception;
	
	int32_t gyx;
	gyx = sensorGyroscopeModalityPreparation_2.xAxisData;
	int32_t gyy;
	gyy = sensorGyroscopeModalityPreparation_2.yAxisData;
	int32_t gyz;
	gyz = sensorGyroscopeModalityPreparation_2.zAxisData;
	uint32_t sensorLightModalityPreparation_3;
	exception = LightSensor_readLuxData(xdkLightSensor_MAX44009_Handle, &sensorLightModalityPreparation_3);
	if(exception != NO_EXCEPTION) return exception;
	
	double light = sensorLightModalityPreparation_3 / 1000.0f;
	Environmental_Data_T sensorEnvironmentModalityPreparation_4;
	exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_4);
	if(exception != NO_EXCEPTION) return exception;
	
	double temperature = sensorEnvironmentModalityPreparation_4.temperature / 1000.0f;
	temperature = temperature - 6.5975f;
	double humidity = sensorEnvironmentModalityPreparation_4.humidity / 1000.0f;
	double pressure = sensorEnvironmentModalityPreparation_4.pressure / 1000.0f;
	char json_buf[281] = {0};
	char *json = json_buf;
	
	char mainHandleEvery10Second12Json_12_buf[281] = {0};
	snprintf(mainHandleEvery10Second12Json_12_buf, sizeof(mainHandleEvery10Second12Json_12_buf), "{\n\t\t\"accx\": %" PRId32 ", \"accy\": %" PRId32 ", \"accz\": %" PRId32 ",\n\t\t\"gyx\": %" PRId32 ", \"gyy\": %" PRId32 ", \"gyz\": %" PRId32 ",\n\t\t\"light\": %.6g, \"temperature\": %.6g,\n\t\t\"humidity\": %.6g, \"pressure\": %.6g\n\t}", accx, accy, accz, gyx, gyy, gyz, light, temperature, humidity, pressure);
	memcpy(json, mainHandleEvery10Second12Json_12_buf, sizeof(mainHandleEvery10Second12Json_12_buf));
	
	char* _newConnectivityMQTTQubitroBroker_QubitroTopik_1 = json;
	exception = ConnectivityMQTTQubitroBroker_QubitroTopik_Write(&_newConnectivityMQTTQubitroBroker_QubitroTopik_1);
	if(exception != NO_EXCEPTION) return exception;
	printf("%s\n", json);


	return NO_EXCEPTION;
}


