/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#ifndef CONNECTIVITYMQTT_MQTT_H
#define CONNECTIVITYMQTT_MQTT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the MQTT.
 */
Retcode_T ConnectivityMQTTQubitroBroker_Setup(void);

/**
 * Enables the MQTT sensor.
 */
Retcode_T ConnectivityMQTTQubitroBroker_Enable(void);

/**
 * Provides read access to qubitroTopik.
 */
Retcode_T ConnectivityMQTTQubitroBroker_QubitroTopik_Read(char** result);

/**
 * Provides write access to qubitroTopik.
 */
Retcode_T ConnectivityMQTTQubitroBroker_QubitroTopik_Write(char** result);


#endif
