/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#ifndef CONNECTIVITYWLAN_WLAN_H
#define CONNECTIVITYWLAN_WLAN_H

#include <BCDS_Retcode.h>


/**
 * Sets up the WLAN.
 */
Retcode_T ConnectivityWLANWifi_Setup(void);

/**
 * Enables the WLAN sensor.
 */
Retcode_T ConnectivityWLANWifi_Enable(void);



#endif
