/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:46
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery10Second1_Enable(void);


#endif
