/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#ifndef SENSORGYROSCOPE_GYROSCOPE_H
#define SENSORGYROSCOPE_GYROSCOPE_H

#include <BCDS_Retcode.h>


/**
 * Sets up the gyroscope.
 */
Retcode_T SensorGyroscope_Setup(void);

/**
 * Enables the gyroscope sensor.
 */
Retcode_T SensorGyroscope_Enable(void);



#endif
