/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#ifndef SENSORLIGHT_LIGHT_H
#define SENSORLIGHT_LIGHT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the light.
 */
Retcode_T SensorLight_Setup(void);

/**
 * Enables the light sensor.
 */
Retcode_T SensorLight_Enable(void);



#endif
