/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2022-04-28 15:45:47
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <BCDS_CalibratedGyro.h>
#include <XdkSensorHandle.h>
#include "MitaExceptions.h"


Retcode_T SensorGyroscope_Setup(void)
{
	Retcode_T exception = RETCODE_OK;
	
	exception = CalibratedGyro_init(xdkCalibratedGyroscope_Handle);
	if(exception != NO_EXCEPTION) return exception;
	
	return NO_EXCEPTION;
}

Retcode_T SensorGyroscope_Enable(void)
{
	
	return NO_EXCEPTION;
}


